### ISSUE TITLE
'YowCelery' object has no attribute 'stack'

### ISSUE THREAD

**Issue by aloka-cuelogic** [jlmadurga/yowsup-celery#1]
Error is happening while I initialize a task.

Login and Logout are successfully working for me.
I am able to receive messages:
    Message id B19CBE89A83C3D8A7620F799CD62CF received

But when I am running send message or any other task I am getting:

```
 'YowCelery' object has no attribute 'stack'
```

StackTrace:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/it149/Envs/try/local/lib/python2.7/site-packages/celery/local.py", line 188, in **call**
    return self._get_current_object()(_a, *_kw)
  File "/home/it149/Envs/try/local/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
    return self.run(_args, *_kwargs)
  File "/home/it149/Envs/try/local/lib/python2.7/site-packages/yowsup_celery/tasks.py", line 9, in decorated_function
    if not self.stack.listening:
  File "/home/it149/Envs/try/local/lib/python2.7/site-packages/yowsup_celery/tasks.py", line 23, in stack
    return self.app.stack
AttributeError: 'YowCelery' object has no attribute 'stack'

**Comment by jlmadurga** [comment]
You must use **delay** when calling `send_message`.

`tasks.send_message.delay("341234567",** "New message sent")'`

There is a typo in docs I will fix it.

Thanks

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

**Comment by aloka-cuelogic** [comment]
Thanks for your quick reply.
Solution worked for me.
I am able to send message now using the library.

But not able to track receiving messages.
Although I am getting my messages id through celery but not able to get exact incoming message.

I am getting message like 

Message id 976BC31556AAB3F31B5F9B95B0EC2D received

**Comment by jlmadurga** [comment]
If you want to perform some action with the received messages you should add an intermediated layer. For example you can set a layer to store message like this https://github.com/jlmadurga/yowlayer-django-store. 
It is explained in docs: https://yowsup-celery.readthedocs.org/en/latest/usage.html
